---
# Tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- hosts: workstation
  connection: local
  become: true

  tasks:
  - name: Install packages
    package:
      name:
      - htop
      - tmux
      - vim-nox
      - python3-psutil
      - dconf-cli
      - gthumb

  - name: Copy wallpaper file
    copy:
      src: files/ontheway.jpg
      dest: /usr/share/backgrounds/ansible-ontheway.jpg
      owner: root
      group: root

  - name: Set wallpaper
    become_user: roberto
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-ontheway.jpg'"

  - name: Set wallpaper position
    become_user: roberto
    dconf:
      key: "/org/gnome/desktop/background/picture-position"
      value: "'scaled'"

  - name: Copy .baschrc file
    copy:
      src: files/bashrc
      dest: /home/roberto/.bashrc
      owner: roberto
      group: roberto

  - name: Copy .zshrc file
    copy:
      src: files/zshrc
      dest: /home/roberto/.zshrc
      owner: roberto
      group: roberto

# End of run cleanup and reporting
- hosts: all
  become: true
  tasks:
  - name: cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: autoremove orphan packages (debian and ubuntu)
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
